# Generated by Django 5.1.7 on 2025-03-10 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('land_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.FloatField(help_text='Area in acres or sq. meters')),
                ('land_type', models.CharField(choices=[('Agricultural', 'Agricultural'), ('Commercial', 'Commercial'), ('Residential', 'Residential')], max_length=100)),
                ('utilities_available', models.TextField(help_text='Electricity, Water, etc.')),
                ('soil_quality', models.CharField(help_text='Soil fertility & type', max_length=255)),
                ('land_access', models.CharField(help_text='Road access, transportation', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('land_status', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Sold', 'Sold')], max_length=50)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='land_images/')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lands.land')),
            ],
        ),
    ]
