# Generated by Django 5.1.7 on 2025-03-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_alter_land_land_status_rentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
