# Generated by Django 5.1.7 on 2025-03-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0003_land_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='seven_twelve_doc',
            field=models.FileField(blank=True, help_text='Upload 7/12 land document', null=True, upload_to='land_documents/'),
        ),
    ]
